# Generated by Django 4.2.11 on 2024-03-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('veg', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('is_vegetarian', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('favorite_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.foodoptions')),
            ],
        ),
        migrations.CreateModel(
            name='FoodWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_served', models.DateTimeField(verbose_name='date')),
                ('meal', models.CharField(max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.foodoptions')),
            ],
        ),
    ]
