# Generated by Django 4.2.11 on 2024-03-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_foodoptions_foodpreferences_foodwaste_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodOptions',
            new_name='FoodOption',
        ),
        migrations.RenameModel(
            old_name='FoodPreferences',
            new_name='FoodPreference',
        ),
    ]
