# Generated by Django 4.2.11 on 2024-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_foodoptions_foodoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwaste',
            name='waste_amount',
            field=models.IntegerField(default=0),
        ),
    ]
